version: '3'

services:

  # Mongo service that runs the MongoDB server container 
  mongodb:
    image : mongo:4.0.4
    container_name: springboot-mongodb
    ports :
      - 27017:27017           # mapping the container's 27017 port to the host machines 27017 port
    volumes :  
    # Please create /data/db directory structure on your host machine if it does not exist already.
      - /data/db:/data/db     # Sharing the hosts database files with the container, so that the data persists even after the container is shut down
    restart: always
    command: mongod --smallfiles --logpath=/dev/null # --quiet

  # ODS service that runs the Maven container
  ods-service:
    build: .
    env_file:
      - .ods.env
    ports:
      - 8080:8080
    depends_on :
      - mongodb         # ensuring that the Maven container is started only after the mongo-service is up
