spring.data.mongodb.username=
spring.data.mongodb.password=
spring.data.mongodb.uri=mongodb://localhost:27017/onedatashare

#OAuth2 Login client details
spring.security.oauth2.client.registration.google.client-id=52271317415-7nid8c1miamrpm0e4od78o24h8rs94uo.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.redirect-uri-template=http://localhost:8080/oauth2/callback/google
spring.security.oauth2.client.registration.github.client-id=d073efb86050f057dfaa
spring.security.oauth2.client.registration.github.client-secret=02dac53d36086dcedde46dc38c910dae4723798d
spring.security.oauth2.client.registration.github.redirect-uri-template=http://localhost:8080/oauth2/callback/github
spring.security.oauth2.client.registration.cilogon.client-id=cilogon:/client_id/7d6a608e8ef8c872dc04240edd43329c
spring.security.oauth2.client.registration.cilogon.client-secret=EYJEZ4D7Y_OvVsGAtSYJ720uo0EWnSprP_I11GdnK2R5O0h5yIfIdMz66CrD1hkzE6OvLCXh6f5Ffj-MeFnZbg
spring.security.oauth2.client.registration.cilogon.authorization-uri=https://cilogon.org/authorize
spring.security.oauth2.client.registration.cilogon.token-uri=https://cilogon.org/oauth2/token
spring.security.oauth2.client.registration.cilogon.userinfo-uri=https://cilogon.org/oauth2/userinfo
spring.security.oauth2.client.registration.cilogon.jwk-set-uri=https://cilogon.org/oauth2/certs
spring.security.oauth2.client.registration.cilogon.redirect-uri-template:http://localhost:8080/oauth2/callback/cilogon

app.oauth2.authorizedRedirectUris=http://localhost:3000/oauth2/redirect